import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { Link, NavLink, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import { QRCodeSVG } from 'qrcode.react'
import { ArrowLeft, ArrowRight, Bot, Check, ChevronDown, CircleHelp, Clock3, Heart, Languages, LockKeyhole, MapPin, Menu, Minus, PackageCheck, Plus, Search, Send, ShieldCheck, ShoppingBag, Sparkles, Trash2, UserRound, X } from 'lucide-react'
import { faqs } from './data'
import { t, type UiKey } from './i18n'
import { createReservation, findReservation, getProducts, getReservations, saveProducts, setReservationStatus } from './store'
import type { CartItem, Category, Locale, Product, Reservation, ReservationStatus } from './types'

const logo='https://dutyfreeshoppuertoiguazu.com/wp-content/uploads/2025/02/Logo-DFSPI_CON-FONDO-2.png'
const hero='https://dutyfreeshoppuertoiguazu.com/wp-content/uploads/2026/02/VPN_AC_Model_Key_Visual_1500×500_26SS-1.jpg'

function usePersisted<T>(key:string,initial:T){const [v,setV]=useState<T>(()=>{try{return JSON.parse(localStorage.getItem(key)||'null')??initial}catch{return initial}});useEffect(()=>localStorage.setItem(key,JSON.stringify(v)),[key,v]);return [v,setV] as const}

export default function App(){
 const [locale,setLocale]=usePersisted<Locale>('dfspi-locale','es')
 const [cart,setCart]=usePersisted<CartItem[]>('dfspi-cart',[])
 const [favorites,setFavorites]=usePersisted<string[]>('dfspi-favorites',[])
 const [chatOpen,setChatOpen]=useState(false)
 const tr=(key:UiKey)=>t(locale,key)
 const add=(id:string)=>setCart(c=>{const found=c.find(i=>i.productId===id);return found?c.map(i=>i.productId===id?{...i,quantity:i.quantity+1}:i):[...c,{productId:id,quantity:1}]})
 return <div className="app"><Header locale={locale} setLocale={setLocale} cartCount={cart.reduce((a,b)=>a+b.quantity,0)} tr={tr}/><main>
  <Routes>
   <Route path="/" element={<Home locale={locale} tr={tr} add={add} favorites={favorites} setFavorites={setFavorites}/>}/>
   <Route path="/catalogo" element={<Catalog locale={locale} tr={tr} add={add} favorites={favorites} setFavorites={setFavorites}/>}/>
   <Route path="/producto/:id" element={<ProductDetail locale={locale} tr={tr} add={add}/>}/>
   <Route path="/seleccion" element={<Cart locale={locale} tr={tr} cart={cart} setCart={setCart}/>}/>
   <Route path="/checkout" element={<Checkout locale={locale} tr={tr} cart={cart} clearCart={()=>setCart([])}/>}/>
   <Route path="/confirmacion" element={<Confirmation locale={locale} tr={tr}/>}/>
   <Route path="/mi-reserva" element={<Lookup locale={locale} tr={tr}/>}/>
   <Route path="/legales" element={<Legal locale={locale}/>}/>
   <Route path="/equipo" element={<Admin locale={locale}/>}/>
   <Route path="*" element={<NotFound/>}/>
  </Routes>
 </main><Footer locale={locale} tr={tr}/><Chat locale={locale} tr={tr} open={chatOpen} setOpen={setChatOpen}/></div>
}

function Header({locale,setLocale,cartCount,tr}:{locale:Locale;setLocale:(v:Locale)=>void;cartCount:number;tr:(k:UiKey)=>string}){
 const [open,setOpen]=useState(false)
 return <><div className="announcement"><span><Sparkles size={14}/> {locale==='es'?'Reservá online y pagá al retirar':'Reserve online e pague na retirada'}</span><span className="announcement-right"><Clock3 size={14}/> {locale==='es'?'Todos los días · 12 a 20 h (AR)':'Todos os dias · 12h às 20h (AR)'}</span></div><header className="header"><Link to="/" className="brand"><img src={logo} alt="Duty Free Shop Puerto Iguazú"/></Link><nav className={open?'nav open':'nav'}>
  <NavLink to="/" onClick={()=>setOpen(false)}>{tr('navHome')}</NavLink><NavLink to="/catalogo" onClick={()=>setOpen(false)}>{tr('navCatalog')}</NavLink><a href="/#como" onClick={()=>setOpen(false)}>{tr('navHow')}</a><a href="/#faq" onClick={()=>setOpen(false)}>{tr('navFaq')}</a><NavLink to="/mi-reserva" onClick={()=>setOpen(false)}>{tr('navReservation')}</NavLink>
 </nav><div className="header-actions"><button className="lang" onClick={()=>setLocale(locale==='es'?'pt':'es')} aria-label="Cambiar idioma"><Languages size={18}/><span>{locale.toUpperCase()}</span></button><Link to="/seleccion" className="cart-button" aria-label={tr('cart')}><ShoppingBag size={20}/>{cartCount>0&&<b>{cartCount}</b>}</Link><button className="menu" onClick={()=>setOpen(!open)} aria-label="Menú">{open?<X/>:<Menu/>}</button></div></header></>
}

const toggle=(xs:string[],id:string)=>xs.includes(id)?xs.filter(x=>x!==id):[...xs,id]
function Home({locale,tr,add,favorites,setFavorites}:{locale:Locale;tr:(k:UiKey)=>string;add:(id:string)=>void;favorites:string[];setFavorites:(f:(v:string[])=>string[])=>void}){
 const ps=getProducts().filter(p=>p.featured).slice(0,5)
 return <><section className="hero"><div className="hero-media"><img src={hero} alt="Experiencia Duty Free"/><div className="hero-shade"/></div><div className="hero-content"><div className="eyebrow">{tr('heroEyebrow')}</div><h1>{tr('heroTitle')}</h1><p>{tr('heroBody')}</p><div className="hero-buttons"><Link className="button gold" to="/catalogo">{tr('explore')} <ArrowRight size={18}/></Link><a className="button ghost" href="#como">{tr('how')}</a></div></div><div className="hero-note"><MapPin size={18}/><span>Ruta 12 · Paso de Frontera<br/><b>Puerto Iguazú, Misiones</b></span></div></section>
 <section className="trust-strip"><div><ShieldCheck/><span><b>{locale==='es'?'Reserva sin pago':'Reserva sem pagamento'}</b><small>{locale==='es'?'Pagá recién en tienda':'Pague somente na loja'}</small></span></div><div><PackageCheck/><span><b>{locale==='es'?'Stock reservado':'Estoque reservado'}</b><small>{locale==='es'?'Hasta el día de retiro':'Até o dia da retirada'}</small></span></div><div><Clock3/><span><b>{locale==='es'?'Retiro ágil':'Retirada rápida'}</b><small>{locale==='es'?'Mostrá tu código QR':'Mostre seu código QR'}</small></span></div></section>
 <section className="section featured"><div className="section-head"><div><span className="kicker">{locale==='es'?'CURADURÍA DFSPI':'CURADORIA DFSPI'}</span><h2>{tr('featured')}</h2><p>{tr('featuredBody')}</p></div><Link to="/catalogo" className="text-link">{locale==='es'?'Ver todo':'Ver tudo'} <ArrowRight size={16}/></Link></div><div className="product-grid">{ps.map(p=><ProductCard key={p.id} product={p} locale={locale} tr={tr} add={add} favorite={favorites.includes(p.id)} onFavorite={()=>setFavorites(v=>toggle(v,p.id))}/>)}</div></section>
 <section id="como" className="how-section"><div className="how-copy"><span className="kicker light">{locale==='es'?'SIMPLE Y SEGURO':'SIMPLES E SEGURO'}</span><h2>{locale==='es'?'Tu selección lista cuando llegues.':'Sua seleção pronta quando você chegar.'}</h2><p>{locale==='es'?'Sin filas, sin pago anticipado y con la tranquilidad de encontrar lo que elegiste.':'Sem filas, sem pagamento antecipado e com a tranquilidade de encontrar o que você escolheu.'}</p><Link to="/catalogo" className="button gold">{tr('reserve')} <ArrowRight size={18}/></Link></div><div className="steps"><Step n="01" title={tr('step1')} body={tr('step1b')}/><Step n="02" title={tr('step2')} body={tr('step2b')}/><Step n="03" title={tr('step3')} body={tr('step3b')}/></div></section>
 <FaqSection locale={locale}/><section className="visit"><div><span className="kicker light">{locale==='es'?'TU PRÓXIMA PARADA':'SUA PRÓXIMA PARADA'}</span><h2>{locale==='es'?'Una experiencia única en la frontera.':'Uma experiência única na fronteira.'}</h2></div><div className="visit-details"><p><MapPin/>Ruta Nacional 12, km 1645,5<br/>Puerto Iguazú, Misiones</p><p><Clock3/>{locale==='es'?'Todos los días':'Todos os dias'}<br/>12:00 — 20:00 (AR)</p></div></section></>
}
function Step({n,title,body}:{n:string;title:string;body:string}){return <div className="step"><span>{n}</span><div><h3>{title}</h3><p>{body}</p></div></div>}

function ProductCard({product:p,locale,tr,add,favorite,onFavorite}:{product:Product;locale:Locale;tr:(k:UiKey)=>string;add:(id:string)=>void;favorite:boolean;onFavorite:()=>void}){
 const [done,setDone]=useState(false);const click=()=>{add(p.id);setDone(true);setTimeout(()=>setDone(false),1200)}
 return <article className="product-card"><div className="product-image"><Link to={`/producto/${p.id}`}><img src={p.image} alt={`${p.brand} ${p.name}`}/></Link>{p.originalPrice&&<span className="sale">-{Math.round((1-p.price/p.originalPrice)*100)}%</span>}<button className={favorite?'heart active':'heart'} onClick={onFavorite} aria-label="Favorito"><Heart size={19}/></button></div><div className="product-info"><span className="brand-name">{p.brand}</span><Link to={`/producto/${p.id}`}><h3>{p.name}</h3></Link><p>{p.subtitle[locale]}</p><div className="availability"><i className={p.stock<5?'low':''}/>{p.stock<5?tr('lastUnits'):tr('available')}</div><div className="product-bottom"><div className="price"><small>USD</small><strong>{p.price}</strong>{p.originalPrice&&<del>${p.originalPrice}</del>}</div><button onClick={click} className={done?'add-button done':'add-button'}>{done?<Check size={19}/>:<Plus size={19}/>}<span>{done?tr('added'):tr('add')}</span></button></div></div></article>
}

function Catalog({locale,tr,add,favorites,setFavorites}:{locale:Locale;tr:(k:UiKey)=>string;add:(id:string)=>void;favorites:string[];setFavorites:(f:(v:string[])=>string[])=>void}){
 const [q,setQ]=useState(''),[cat,setCat]=useState<'all'|Category>('all'), ps=getProducts();const filtered=ps.filter(p=>(cat==='all'||p.category===cat)&&`${p.brand} ${p.name}`.toLowerCase().includes(q.toLowerCase()))
 const cats:(['all'|Category,UiKey])[]=[['all','all'],['perfumes','perfumes'],['bebidas','bebidas'],['delicatessen','delicatessen'],['tecnologia','tecnologia']]
 return <div className="page catalog-page"><div className="page-title"><span className="kicker">DUTY FREE COLLECTION</span><h1>{locale==='es'?'Encontrá tu próximo favorito.':'Encontre seu próximo favorito.'}</h1><p>{locale==='es'?'Precios exclusivos, marcas internacionales y retiro en tienda.':'Preços exclusivos, marcas internacionais e retirada na loja.'}</p></div><div className="catalog-tools"><label className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={tr('search')}/></label><div className="categories">{cats.map(([id,key])=><button key={id} className={cat===id?'active':''} onClick={()=>setCat(id)}>{tr(key)}</button>)}</div></div><div className="catalog-meta"><span>{filtered.length} {locale==='es'?'productos':'produtos'}</span><span>{locale==='es'?'Ordenar: Recomendados':'Ordenar: Recomendados'} <ChevronDown size={15}/></span></div><div className="product-grid catalog-grid">{filtered.map(p=><ProductCard key={p.id} product={p} locale={locale} tr={tr} add={add} favorite={favorites.includes(p.id)} onFavorite={()=>setFavorites(v=>toggle(v,p.id))}/>)}</div>{!filtered.length&&<div className="empty"><Search/><h2>{locale==='es'?'No encontramos resultados':'Nenhum resultado encontrado'}</h2></div>}</div>
}

function ProductDetail({locale,tr,add}:{locale:Locale;tr:(k:UiKey)=>string;add:(id:string)=>void}){const {id}=useParams(),nav=useNavigate(),p=getProducts().find(x=>x.id===id),[qty,setQty]=useState(1);if(!p)return <NotFound/>;return <div className="page detail-page"><button className="back" onClick={()=>nav(-1)}><ArrowLeft/> {locale==='es'?'Volver':'Voltar'}</button><div className="detail-grid"><div className="detail-image"><img src={p.image} alt={`${p.brand} ${p.name}`}/></div><div className="detail-copy"><span className="brand-name">{p.brand}</span><h1>{p.name}</h1><p className="product-subtitle">{p.subtitle[locale]}</p><div className="detail-price"><small>USD</small><strong>{p.price}</strong>{p.originalPrice&&<del>USD {p.originalPrice}</del>}</div><div className="availability big"><i className={p.stock<5?'low':''}/>{p.stock<5?tr('lastUnits'):tr('available')} · {p.stock} {locale==='es'?'en stock':'em estoque'}</div><p className="description">{p.description[locale]}</p><div className="quantity"><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus/></button><span>{qty}</span><button onClick={()=>setQty(Math.min(p.stock,qty+1))}><Plus/></button></div><button className="button navy wide" onClick={()=>{for(let i=0;i<qty;i++)add(p.id);nav('/seleccion')}}><ShoppingBag/> {tr('add')}</button><div className="detail-benefits"><p><ShieldCheck/> {locale==='es'?'Sin pago anticipado':'Sem pagamento antecipado'}</p><p><Clock3/> {locale==='es'?'Retiro hasta 7 días':'Retirada em até 7 dias'}</p></div></div></div></div>}

function Cart({locale,tr,cart,setCart}:{locale:Locale;tr:(k:UiKey)=>string;cart:CartItem[];setCart:(v:CartItem[]|((x:CartItem[])=>CartItem[]))=>void}){const ps=getProducts(),items=cart.map(i=>({...i,product:ps.find(p=>p.id===i.productId)!})).filter(i=>i.product);const total=items.reduce((s,i)=>s+i.product.price*i.quantity,0);if(!items.length)return <div className="page empty"><ShoppingBag/><h1>{tr('emptyCart')}</h1><p>{tr('emptyCartBody')}</p><Link to="/catalogo" className="button navy">{tr('continue')}</Link></div>;const update=(id:string,q:number)=>setCart(q<1?cart.filter(i=>i.productId!==id):cart.map(i=>i.productId===id?{...i,quantity:Math.min(q,ps.find(p=>p.id===id)?.stock||q)}:i));return <div className="page cart-page"><div className="page-title left"><span className="kicker">{locale==='es'?'TU RESERVA':'SUA RESERVA'}</span><h1>{tr('cart')}</h1></div><div className="cart-layout"><div className="cart-items">{items.map(i=><div className="cart-row" key={i.productId}><img src={i.product.image}/><div className="cart-product"><small>{i.product.brand}</small><h3>{i.product.name}</h3><p>{i.product.subtitle[locale]}</p><button onClick={()=>update(i.productId,0)}><Trash2/> {tr('remove')}</button></div><div className="cart-qty"><button onClick={()=>update(i.productId,i.quantity-1)}><Minus/></button><span>{i.quantity}</span><button onClick={()=>update(i.productId,i.quantity+1)}><Plus/></button></div><strong>USD {i.product.price*i.quantity}</strong></div>)}</div><aside className="summary-card"><h2>{tr('summary')}</h2><div><span>{items.length} {tr('items')}</span><span>USD {total}</span></div><hr/><div className="summary-total"><span>{tr('subtotal')}</span><strong>USD {total}</strong></div><p><ShieldCheck/> {tr('payStore')}</p><Link to="/checkout" className="button gold wide">{tr('checkout')} <ArrowRight/></Link></aside></div></div>}

function Checkout({locale,tr,cart,clearCart}:{locale:Locale;tr:(k:UiKey)=>string;cart:CartItem[];clearCart:()=>void}){const nav=useNavigate(),[busy,setBusy]=useState(false),[error,setError]=useState('');const min=new Date();min.setDate(min.getDate()+1);const max=new Date();max.setDate(max.getDate()+7);const iso=(d:Date)=>d.toISOString().slice(0,10);if(!cart.length)return <Cart locale={locale} tr={tr} cart={[]} setCart={()=>{}}/>;const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);setError('');const fd=new FormData(e.currentTarget);try{const r=createReservation({name:String(fd.get('name')),email:String(fd.get('email')),phone:String(fd.get('phone'))},String(fd.get('pickup')),cart,locale);sessionStorage.setItem('dfspi-last-reservation',JSON.stringify(r));clearCart();nav('/confirmacion')}catch{setError(locale==='es'?'La disponibilidad cambió. Revisá tu selección.':'A disponibilidade mudou. Revise sua seleção.')}finally{setBusy(false)}};return <div className="page checkout-page"><div className="checkout-intro"><span className="kicker">CHECKOUT</span><h1>{tr('checkoutTitle')}</h1><p>{tr('checkoutBody')}</p></div><form className="checkout-form" onSubmit={submit}><div className="form-card"><h2><UserRound/> {locale==='es'?'Tus datos':'Seus dados'}</h2><div className="field-grid"><label><span>{tr('name')}</span><input name="name" required minLength={3} autoComplete="name"/></label><label><span>{tr('email')}</span><input name="email" type="email" required autoComplete="email"/></label><label><span>{tr('phone')}</span><input name="phone" type="tel" required minLength={7} autoComplete="tel"/></label><label><span>{tr('pickup')}</span><input name="pickup" type="date" min={iso(min)} max={iso(max)} defaultValue={iso(min)} required/></label></div></div><div className="form-card"><h2><PackageCheck/> {locale==='es'?'Retiro en tienda':'Retirada na loja'}</h2><div className="pickup-box"><MapPin/><div><b>Duty Free Shop Puerto Iguazú</b><p>Ruta Nacional 12, km 1645,5 · Paso de Frontera</p><small>{locale==='es'?'Todos los días, 12:00 a 20:00 (hora argentina)':'Todos os dias, 12h às 20h (horário argentino)'}</small></div></div></div><label className="terms"><input type="checkbox" required/><span>{tr('terms')} <Link to="/legales">{locale==='es'?'Leer condiciones':'Ler condições'}</Link></span></label>{error&&<p className="form-error">{error}</p>}<button className="button gold wide submit" disabled={busy}>{busy?(locale==='es'?'Confirmando...':'Confirmando...'):tr('confirm')} <ArrowRight/></button><p className="secure"><LockKeyhole/> {tr('secure')}</p></form></div>}

function Confirmation({locale,tr}:{locale:Locale;tr:(k:UiKey)=>string}){let r:Reservation|null=null;try{r=JSON.parse(sessionStorage.getItem('dfspi-last-reservation')||'null')}catch{}if(!r)return <NotFound/>;return <div className="page confirmation"><div className="success-icon"><Check/></div><span className="kicker">{locale==='es'?'RESERVA COMPLETA':'RESERVA CONCLUÍDA'}</span><h1>{tr('success')}</h1><p>{tr('successBody')}</p><div className="ticket"><div className="ticket-logo"><img src={logo}/></div><div className="qr"><QRCodeSVG value={`DFSPI:${r.code}:${r.customer.email}`} size={148}/></div><small>{tr('code')}</small><strong className="reservation-code">{r.code}</strong><div className="ticket-info"><span>{tr('pickup')}<b>{new Date(r.pickupDate+'T12:00:00').toLocaleDateString(locale==='es'?'es-AR':'pt-BR',{weekday:'long',day:'numeric',month:'long'})}</b></span><span>{tr('subtotal')}<b>USD {r.total}</b></span></div></div><p className="email-note"><Send/> {tr('emailSent')} <b>{r.customer.email}</b></p><div className="confirmation-actions"><Link className="button navy" to="/">{tr('backHome')}</Link><Link className="button outline" to="/mi-reserva">{tr('navReservation')}</Link></div></div>}

function StatusBadge({status}:{status:ReservationStatus}){return <span className={`status ${status}`}>{status.replaceAll('_',' ')}</span>}
function ReservationView({r,locale}:{r:Reservation;locale:Locale}){const ps=getProducts();return <div className="reservation-view"><div><span>{locale==='es'?'Reserva':'Reserva'} <b>{r.code}</b></span><StatusBadge status={r.status}/></div><p><CalendarIcon/> {new Date(r.pickupDate+'T12:00:00').toLocaleDateString(locale==='es'?'es-AR':'pt-BR',{dateStyle:'long'})}</p>{r.items.map(i=>{const p=ps.find(x=>x.id===i.productId);return p?<div className="mini-item" key={i.productId}><img src={p.image}/><span>{p.brand}<b>{p.name}</b></span><strong>{i.quantity} × USD {p.price}</strong></div>:null})}<div className="mini-total"><span>Total</span><b>USD {r.total}</b></div></div>}
function CalendarIcon(){return <Clock3 size={18}/>}
function Lookup({locale,tr}:{locale:Locale;tr:(k:UiKey)=>string}){const [result,setResult]=useState<Reservation|null|undefined>(undefined),submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);setResult(findReservation(String(fd.get('code')),String(fd.get('email')))||null)};return <div className="lookup-page"><div className="lookup-card"><div className="lookup-icon"><Search/></div><h1>{tr('lookupTitle')}</h1><p>{tr('lookupBody')}</p><form onSubmit={submit}><label><span>{tr('code')}</span><input name="code" placeholder="IGZ-XXXX-XXXX" required/></label><label><span>{tr('email')}</span><input name="email" type="email" required/></label><button className="button gold wide">{tr('lookup')} <ArrowRight/></button></form>{result===null&&<p className="not-found">{tr('notFound')}</p>}{result&&<ReservationView r={result} locale={locale}/>}</div></div>}

function FaqSection({locale}:{locale:Locale}){const [open,setOpen]=useState(faqs[0].id);return <section id="faq" className="section faq-section"><div className="section-head"><div><span className="kicker">FAQ</span><h2>{locale==='es'?'Antes de viajar, resolvé tus dudas.':'Antes de viajar, tire suas dúvidas.'}</h2></div><Link to="/mi-reserva" className="text-link">{locale==='es'?'Consultar reserva':'Consultar reserva'} <ArrowRight/></Link></div><div className="faq-list">{faqs.map(f=><button key={f.id} className={open===f.id?'faq-item open':'faq-item'} onClick={()=>setOpen(open===f.id?'':f.id)}><span>{f.question[locale]}</span><Plus/>{open===f.id&&<p>{f.answer[locale]}</p>}</button>)}</div></section>}

type Message={from:'bot'|'user';text:string}
function Chat({locale,tr,open,setOpen}:{locale:Locale;tr:(k:UiKey)=>string;open:boolean;setOpen:(v:boolean)=>void}){const [messages,setMessages]=useState<Message[]>([{from:'bot',text:locale==='es'?'¡Hola! Soy el asistente de DFSPI. ¿En qué puedo ayudarte?':'Olá! Sou o assistente do DFSPI. Como posso ajudar?'}]),[text,setText]=useState('');useEffect(()=>setMessages([{from:'bot',text:locale==='es'?'¡Hola! Soy el asistente de DFSPI. ¿En qué puedo ayudarte?':'Olá! Sou o assistente do DFSPI. Como posso ajudar?'}]),[locale]);const reply=(value:string)=>{if(!value.trim())return;const norm=value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const found=faqs.find(f=>f.keywords[locale].some(k=>norm.includes(k)));setMessages(m=>[...m,{from:'user',text:value},{from:'bot',text:found?found.answer[locale]:tr('fallback')}]);setText('')};return <><button className="chat-launcher" onClick={()=>setOpen(!open)} aria-label={tr('navFaq')}>{open?<X/>:<Bot/>}<span>{locale==='es'?'¿Necesitás ayuda?':'Precisa de ajuda?'}</span></button>{open&&<aside className="chat"><div className="chat-head"><div><Bot/><span><b>Asistente DFSPI</b><small><i/> {locale==='es'?'En línea':'Online'}</small></span></div><button onClick={()=>setOpen(false)}><X/></button></div><div className="chat-body">{messages.map((m,i)=><div key={i} className={`message ${m.from}`}>{m.text}</div>)}{messages.length<3&&<div className="suggestions">{faqs.slice(0,3).map(f=><button key={f.id} onClick={()=>reply(f.question[locale])}>{f.question[locale]}</button>)}</div>}</div><form className="chat-form" onSubmit={e=>{e.preventDefault();reply(text)}}><input value={text} onChange={e=>setText(e.target.value)} placeholder={tr('ask')}/><button aria-label={tr('send')}><Send/></button></form><div className="chat-safe"><ShieldCheck/> {locale==='es'?'Respuestas oficiales y verificadas':'Respostas oficiais e verificadas'}</div></aside>}</>}

function Legal({locale}:{locale:Locale}){return <div className="page legal"><span className="kicker">{locale==='es'?'INFORMACIÓN LEGAL':'INFORMAÇÃO LEGAL'}</span><h1>{locale==='es'?'Condiciones de reserva y privacidad':'Condições de reserva e privacidade'}</h1>{(locale==='es'?[
 ['Naturaleza de la reserva','La reserva aparta productos hasta el cierre de la fecha elegida. No constituye una compra ni requiere pago online. Los precios se expresan en dólares estadounidenses y el pago se completa en tienda.'],['Retiro y vencimiento','La persona titular debe presentar el código de reserva y documentación válida. Las reservas no retiradas se cancelan automáticamente al finalizar el día seleccionado.'],['Disponibilidad y límites','El stock se descuenta al confirmar. DFSPI podrá cancelar una reserva por errores manifiestos de inventario, informando al cliente por email. La compra está sujeta a franquicias aduaneras y no puede presumir fin comercial.'],['Datos personales','Nombre, email y teléfono se utilizan para administrar la reserva y comunicaciones relacionadas. No se venden a terceros. El titular puede solicitar acceso o eliminación escribiendo a info@dfspi.com.'],['Cambios','Los productos adquiridos en tienda se cambian por fallas de fabricación, sin uso, con embalaje y ticket originales, según el plazo informado en tienda.']
 ]:[['Natureza da reserva','A reserva separa produtos até o fechamento da data escolhida. Não constitui compra nem exige pagamento online. Os preços estão em dólares e o pagamento é feito na loja.'],['Retirada e vencimento','O titular deve apresentar o código e documentação válida. Reservas não retiradas são canceladas automaticamente ao fim do dia escolhido.'],['Disponibilidade e limites','O estoque é descontado na confirmação. O DFSPI pode cancelar por erro manifesto de inventário, avisando por email. A compra está sujeita às franquias aduaneiras.'],['Dados pessoais','Nome, email e telefone são usados para administrar a reserva e comunicações relacionadas. O titular pode solicitar acesso ou exclusão em info@dfspi.com.'],['Trocas','Produtos comprados na loja são trocados por defeito de fabricação, sem uso, com embalagem e comprovante originais, conforme prazo informado na loja.']]).map(([h,p])=><section key={h}><h2>{h}</h2><p>{p}</p></section>)}</div>}

function Admin({locale}:{locale:Locale}){const [auth,setAuth]=useState(()=>sessionStorage.getItem('dfspi-admin')==='1'),[tab,setTab]=useState<'reservas'|'productos'>('reservas'),[refresh,setRefresh]=useState(0);void refresh;if(!auth)return <AdminLogin locale={locale} onLogin={()=>{sessionStorage.setItem('dfspi-admin','1');setAuth(true)}}/>;const rs=getReservations(),ps=getProducts();const statusList:ReservationStatus[]=['confirmada','lista_para_retirar','retirada','cancelada','vencida'];const updateStock=(p:Product,n:number)=>{saveProducts(ps.map(x=>x.id===p.id?{...x,stock:Math.max(0,n)}:x));setRefresh(x=>x+1)};return <div className="admin-page"><aside className="admin-nav"><img src={logo}/><span>{locale==='es'?'PANEL INTERNO':'PAINEL INTERNO'}</span><button className={tab==='reservas'?'active':''} onClick={()=>setTab('reservas')}><PackageCheck/> Reservas <b>{rs.filter(r=>r.status==='confirmada').length}</b></button><button className={tab==='productos'?'active':''} onClick={()=>setTab('productos')}><ShoppingBag/> Productos</button><button onClick={()=>{sessionStorage.removeItem('dfspi-admin');setAuth(false)}}><LockKeyhole/> {locale==='es'?'Cerrar sesión':'Sair'}</button></aside><section className="admin-content"><div className="admin-title"><div><small>DFSPI · Puerto Iguazú</small><h1>{tab==='reservas'?'Reservas':'Catálogo e inventario'}</h1></div><div className="admin-user">CM <span><b>Content Manager</b><small>Operaciones</small></span></div></div>{tab==='reservas'?<><div className="stats"><Stat label="Confirmadas" value={rs.filter(r=>r.status==='confirmada').length}/><Stat label="Listas" value={rs.filter(r=>r.status==='lista_para_retirar').length}/><Stat label="Retiradas" value={rs.filter(r=>r.status==='retirada').length}/><Stat label="Total USD" value={`$${rs.reduce((s,r)=>s+r.total,0)}`}/></div><div className="admin-table-wrap"><table><thead><tr><th>Código</th><th>Cliente</th><th>Retiro</th><th>Productos</th><th>Total</th><th>Estado</th></tr></thead><tbody>{rs.map(r=><tr key={r.code}><td><b>{r.code}</b></td><td>{r.customer.name}<small>{r.customer.email}</small></td><td>{new Date(r.pickupDate+'T12:00').toLocaleDateString()}</td><td>{r.items.reduce((s,i)=>s+i.quantity,0)}</td><td>USD {r.total}</td><td><select value={r.status} onChange={e=>{setReservationStatus(r.code,e.target.value as ReservationStatus);setRefresh(x=>x+1)}}>{statusList.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></td></tr>)}{!rs.length&&<tr><td colSpan={6} className="no-data">Todavía no hay reservas.</td></tr>}</tbody></table></div></>:<div className="admin-products">{ps.map(p=><div key={p.id}><img src={p.image}/><span><small>{p.brand}</small><b>{p.name}</b><em>USD {p.price}</em></span><label>Stock <input type="number" min="0" value={p.stock} onChange={e=>updateStock(p,Number(e.target.value))}/></label></div>)}</div>}</section></div>}
function Stat({label,value}:{label:string;value:string|number}){return <div className="stat"><small>{label}</small><strong>{value}</strong></div>}
function AdminLogin({locale,onLogin}:{locale:Locale;onLogin:()=>void}){const [error,setError]=useState(false);return <div className="admin-login"><form onSubmit={e=>{e.preventDefault();const fd=new FormData(e.currentTarget);if(fd.get('email')==='equipo@dfspi.com'&&fd.get('password')===(import.meta.env.VITE_ADMIN_DEMO_PASSWORD||'dfspi2026'))onLogin();else setError(true)}}><img src={logo}/><div className="lookup-icon"><LockKeyhole/></div><h1>{locale==='es'?'Acceso del equipo':'Acesso da equipe'}</h1><p>{locale==='es'?'Gestioná reservas, catálogo y stock.':'Gerencie reservas, catálogo e estoque.'}</p><label><span>Email</span><input type="email" name="email" defaultValue="equipo@dfspi.com" required/></label><label><span>{locale==='es'?'Contraseña':'Senha'}</span><input type="password" name="password" required/></label>{error&&<p className="form-error">Credenciales incorrectas.</p>}<button className="button gold wide">{locale==='es'?'Ingresar':'Entrar'} <ArrowRight/></button><small className="demo-hint">Demo: equipo@dfspi.com · dfspi2026</small></form></div>}

function Footer({locale,tr}:{locale:Locale;tr:(k:UiKey)=>string}){return <footer><div className="footer-main"><div className="footer-brand"><img src={logo}/><p>{tr('footerBody')}</p></div><div><h4>{tr('store')}</h4><Link to="/catalogo">{tr('navCatalog')}</Link><Link to="/mi-reserva">{tr('navReservation')}</Link><a href="/#como">{tr('navHow')}</a></div><div><h4>{tr('help')}</h4><a href="/#faq">FAQs</a><Link to="/legales">{locale==='es'?'Condiciones':'Condições'}</Link><a href="mailto:info@dfspi.com">Contacto</a></div><div><h4>{locale==='es'?'Visitános':'Visite-nos'}</h4><p>Ruta Nacional 12, km 1645,5<br/>Puerto Iguazú · Misiones<br/>+54 3757 421050</p></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} DFSPI · {tr('rights')}</span><Link to="/equipo">{tr('admin')}</Link><a href="https://londonsupplygroup.com" target="_blank">Una empresa de <b>London Supply Group</b></a></div></footer>}
function NotFound(){return <div className="page empty"><CircleHelp/><h1>Página no encontrada</h1><Link to="/" className="button navy">Volver al inicio</Link></div>}
