import type { Faq, Product } from './types'
export const products:Product[] = [
 {id:'ch-212',brand:'Carolina Herrera',name:'212 VIP Rosé Elixir',subtitle:{es:'Eau de Parfum · 50 ml',pt:'Eau de Parfum · 50 ml'},category:'perfumes',image:'img/ch-212.jpeg',price:89,originalPrice:109,stock:8,featured:true,description:{es:'Una fragancia floral intensa y luminosa, perfecta para celebrar cada viaje.',pt:'Uma fragrância floral intensa e luminosa, perfeita para celebrar cada viagem.'}},
 {id:'armani-way',brand:'Giorgio Armani',name:'My Way',subtitle:{es:'Eau de Parfum · 90 ml',pt:'Eau de Parfum · 90 ml'},category:'perfumes',image:'img/armani-way.jpeg',price:118,stock:5,featured:true,description:{es:'Un bouquet floral contemporáneo con notas de azahar y vainilla.',pt:'Um buquê floral contemporâneo com notas de flor de laranjeira e baunilha.'}},
 {id:'amor-amor',brand:'Cacharel',name:'Amor Amor',subtitle:{es:'Eau de Toilette · 50 ml',pt:'Eau de Toilette · 50 ml'},category:'perfumes',image:'img/amor-amor.jpeg',price:64,originalPrice:76,stock:12,featured:true,description:{es:'Frutal y vibrante, un clásico joven con personalidad.',pt:'Frutado e vibrante, um clássico jovem com personalidade.'}},
 {id:'moncler-sunrise',brand:'Moncler',name:'Sunrise Pour Homme',subtitle:{es:'Eau de Parfum · 100 ml',pt:'Eau de Parfum · 100 ml'},category:'perfumes',image:'img/moncler-sunrise.jpeg',price:132,stock:3,featured:true,description:{es:'Amaderada y sofisticada, inspirada en la energía de la montaña.',pt:'Amadeirada e sofisticada, inspirada na energia da montanha.'}},
 {id:'chivas-12',brand:'Chivas Regal',name:'Chivas Regal 12 Years',subtitle:{es:'Blended Scotch Whisky · 1 L',pt:'Blended Scotch Whisky · 1 L'},category:'bebidas',image:'img/chivas-12.png',price:39,originalPrice:46,stock:18,featured:true,description:{es:'Whisky escocés suave, con notas de miel, vainilla y frutas maduras.',pt:'Whisky escocês suave, com notas de mel, baunilha e frutas maduras.'}},
 {id:'jw-black',brand:'Johnnie Walker',name:'Black Label 12 Years',subtitle:{es:'Blended Scotch Whisky · 1 L',pt:'Blended Scotch Whisky · 1 L'},category:'bebidas',image:'img/jw-black.png',price:42,stock:14,description:{es:'Profundo y equilibrado, con carácter ahumado.',pt:'Profundo e equilibrado, com caráter defumado.'}},
 {id:'jager',brand:'Jägermeister',name:'Herb Liqueur',subtitle:{es:'Licor de hierbas · 1 L',pt:'Licor de ervas · 1 L'},category:'bebidas',image:'img/jager.png',price:25,stock:10,description:{es:'La receta icónica de 56 botánicos.',pt:'A receita icônica de 56 botânicos.'}},
 {id:'amarula',brand:'Amarula',name:'Cream Liqueur',subtitle:{es:'Licor crema · 750 ml',pt:'Licor cremoso · 750 ml'},category:'bebidas',image:'img/amarula.png',price:18,stock:16,description:{es:'Cremoso y suave, elaborado con fruta marula.',pt:'Cremoso e suave, elaborado com a fruta marula.'}},
 {id:'lindt-gold',brand:'Lindt',name:'Swiss Luxury Selection',subtitle:{es:'Bombones surtidos · 230 g',pt:'Bombons sortidos · 230 g'},category:'delicatessen',image:'img/lindt-gold.png',price:22,stock:20,description:{es:'Selección premium de chocolates suizos.',pt:'Seleção premium de chocolates suíços.'}},
 {id:'airpods',brand:'Apple',name:'AirPods Pro',subtitle:{es:'2ª generación · USB-C',pt:'2ª geração · USB-C'},category:'tecnologia',image:'img/airpods.png',price:249,stock:4,description:{es:'Audio adaptativo y cancelación activa de ruido.',pt:'Áudio adaptativo e cancelamento ativo de ruído.'}}
]
export const faqs:Faq[] = [
 {id:'how',question:{es:'¿Cómo funciona la reserva?',pt:'Como funciona a reserva?'},answer:{es:'Elegí tus productos, seleccioná una fecha dentro de los próximos 7 días y confirmá. No pagás online: abonás al retirar presentando tu código y documentación.',pt:'Escolha os produtos, selecione uma data nos próximos 7 dias e confirme. Você não paga online: paga na retirada apresentando o código e a documentação.'},keywords:{es:['reservar','reserva','funciona','comprar'],pt:['reservar','reserva','funciona','comprar']}},
 {id:'hours',question:{es:'¿Cuáles son los horarios?',pt:'Quais são os horários?'},answer:{es:'Abrimos todos los días de 12:00 a 20:00, hora argentina. Los horarios especiales se informan en este sitio.',pt:'Abrimos todos os dias das 12h às 20h, horário argentino. Horários especiais são informados neste site.'},keywords:{es:['horario','hora','abren','cierran'],pt:['horario','hora','abrem','fecham']}},
 {id:'location',question:{es:'¿Dónde retiro mi reserva?',pt:'Onde retiro minha reserva?'},answer:{es:'En Duty Free Shop Puerto Iguazú, Ruta Nacional 12 km 1645,5, Paso de Frontera. Presentá el QR en el punto de Reservas Online.',pt:'No Duty Free Shop Puerto Iguazú, Ruta Nacional 12 km 1645,5, fronteira. Apresente o QR no ponto de Reservas Online.'},keywords:{es:['donde','ubicacion','retirar','direccion'],pt:['onde','localizacao','retirar','endereco']}},
 {id:'payment',question:{es:'¿Qué medios de pago aceptan?',pt:'Quais meios de pagamento aceitam?'},answer:{es:'En tienda podés pagar con Visa, Mastercard, Amex, débito, PIX y efectivo en USD, ARS o BRL. La reserva no requiere pago previo.',pt:'Na loja você pode pagar com Visa, Mastercard, Amex, débito, PIX e dinheiro em USD, ARS ou BRL. A reserva não exige pagamento antecipado.'},keywords:{es:['pago','tarjeta','efectivo','pix','precio'],pt:['pagamento','cartao','dinheiro','pix','preco']}},
 {id:'expiry',question:{es:'¿Hasta cuándo guardan mi reserva?',pt:'Até quando guardam minha reserva?'},answer:{es:'La guardamos hasta el cierre de la fecha de retiro elegida. Después se libera automáticamente el stock.',pt:'Guardamos até o fechamento da data escolhida para retirada. Depois o estoque é liberado automaticamente.'},keywords:{es:['vence','vencimiento','guardar'],pt:['vence','vencimento','guardar']}},
 {id:'docs',question:{es:'¿Qué documentación necesito?',pt:'Quais documentos são necessários?'},answer:{es:'Para ingresar al predio debés registrar la salida en la aduana de tu país de procedencia y presentar la documentación migratoria exigida.',pt:'Para entrar, você deve registrar a saída na aduana do país de origem e apresentar a documentação migratória exigida.'},keywords:{es:['documento','aduana','dni','pasaporte','ingresar'],pt:['documento','aduana','passaporte','entrar']}}
]
